CHI-29 добавлены страницы форума, типизация svg, scss, правило stylelint
Chillout-team/chillout2048 pull request #12
Opened 2023-04-04 18:01 UTC by KupuM

CHI-29 Вёрстка страницы форума.

Список тем:
<img width="500" alt="Снимок экрана 2023-04-04 в 20 57 48" src="https://user-images.githubusercontent.com/4299255/229878371-205ebcf3-4885-4835-849b-38c7f711ba60.png">

Список сообщений:
<img width="500" alt="Снимок экрана 2023-04-04 в 20 59 47" src="https://user-images.githubusercontent.com/4299255/229878705-d4aafc4f-4379-47e5-8948-e8788cb95289.png">

2023-04-04 19:08 UTC, MariaEvdokimova commented on yarn.lock
> +  resolved "https://registry.npmjs.org/@babel/runtime/-/runtime-7.21.0.tgz"
Ты видимо устанавливал пакеты через npm, а не yarn. Тут вроде все через yarn, наверное так конфликты будут

2023-04-05 04:27 UTC, kenzhegaliyevn approved these changes

2023-04-05 06:13 UTC, KupuM commented on yarn.lock
> +  resolved "https://registry.npmjs.org/@babel/runtime/-/runtime-7.21.0.tgz"
Было такое с 1 пакетом, потом удалил, исправлю. Спасибо.

2023-04-05 07:27 UTC, MariaEvdokimova approved these changes
Ок

2023-04-05 08:58 UTC, Lyatifov requested changes

2023-04-05 08:58 UTC, Lyatifov commented on packages/client/src/components/common/textarea/TextArea.tsx
> +import React, { FC, TextareaHTMLAttributes } from 'react';
Есть ли смысл держать импорты которые не используются? `React`

2023-04-05 08:58 UTC, Lyatifov commented on packages/client/src/components/forum/forumForm/ForumForm.tsx
> +        if (formText.trim() !== '') {
Я точно не уверен насколько оправдан такой стиль, но `formText.trim() !== ''` можно заменить на `formText.trim()`

2023-04-05 08:58 UTC, Lyatifov commented on packages/client/src/components/forum/forumTopicsList/ForumTopicsList.tsx
> +            {topics ? (
В `topics` при любом случае придет массив, `[ ] = true`.

2023-04-05 10:31 UTC, KupuM commented on packages/client/src/components/common/textarea/TextArea.tsx
> +import React, { FC, TextareaHTMLAttributes } from 'react';
Без импорта React, VS Code ругался на типы. Оказалось, что VS Code игнорировал настройки из  packages/client/tsconfig.json. Может кому-то понадобится, тут решение:
https://stackoverflow.com/questions/38268776/why-does-typescript-ignore-my-tsconfig-json-inside-visual-studio-code
Импорты уберу, спасибо.

2023-04-05 10:35 UTC, KupuM commented on packages/client/src/components/forum/forumForm/ForumForm.tsx
> +        if (formText.trim() !== '') {
Просто, чтобы понятно было что тут происходит, но если все легко читается, то уберу неравенство.

2023-04-05 10:47 UTC, KupuM commented on packages/client/src/components/forum/forumTopicsList/ForumTopicsList.tsx
> +            {topics ? (
Да, спасибо. Можно подумать на счет добавления lodash в проект.

2023-04-05 11:22 UTC, Lyatifov approved these changes
Замечаний нет.

2023-04-06 10:07 UTC, iapolya approved these changes
Отлично! 

Апрувлю и прошу самостоятельно внести правка, о которых писала Маша:
1. Пути
2. Структура проекта
3. Алиасы 

+ заметила, что у вас в команде разные форматы написания классов в scss модулях. На досуге можете и это обсудить

2023-04-06 10:07 UTC, iapolya commented on packages/client/src/components/forum/forumForm/ForumForm.tsx
> +    let placeholder: string;
Можно сократить до такой конструкции. Она чуть короче + в случае необходимости её проще будет вынести из компонента 

```
const formInfo = {
  message: {
    placeholder: '',
  },
  topic: {
    placeholder: '',
  },
}[type];
```

2023-04-06 10:11 UTC, KupuM commented on packages/client/src/components/forum/forumForm/ForumForm.tsx
> +    /** Обработчик отправки формы. */
Больше не буду обработчики комментировать.

2023-04-06 10:12 UTC, KupuM commented on packages/client/src/components/forum/forumForm/ForumForm.tsx
> +    let placeholder: string;
Спасибо.

2023-04-06 10:44 UTC, iapolya commented on packages/client/src/components/forum/forumForm/ForumForm.tsx
> +    /** Обработчик отправки формы. */
Ок добавлять комменты, когда они дополняют код и помогают лучше его понять. Если же коммент просто дублирует то, что уже в коде написано, то он лишний

2023-04-07 08:53 UTC, merged